package com.courses.lesson16;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Created by ibilous on 01.12.2015.
 */
public class NameListHolder {
    
    public static final String NAMES = "MARY      " +
            "PATRICIA  " +
            "LINDA     " +
            "BARBARA   " +
            "ELIZABETH " +
            "JENNIFER  " +
            "MARIA     " +
            "SUSAN     " +
            "MARGARET  " +
            "DOROTHY   " +
            "LISA      " +
            "NANCY     " +
            "KAREN     " +
            "BETTY     " +
            "HELEN     " +
            "SANDRA    " +
            "DONNA     " +
            "CAROL     " +
            "RUTH      " +
            "SHARON    " +
            "MICHELLE  " +
            "LAURA     " +
            "SARAH     " +
            "KIMBERLY  " +
            "DEBORAH   " +
            "JESSICA   " +
            "SHIRLEY   " +
            "CYNTHIA   " +
            "ANGELA    " +
            "MELISSA  " +
            "DOROTHY   " +
            "ELIZABETH " +
            "JENNIFER  " +
            "MARIA     " +
            "SUSAN     " +
            "MARGARET  " +
            "DOROTHY   " +
            "LISA      " +
            "NANCY     " +
            "KAREN     " +
            "BETTY     " +
            "HELEN     " +
            "SANDRA    " +
            "DONNA     " +
            "CAROL     " +
            "RUTH      " +
            "SHARON    " +
            "MICHELLE  " +
            "LAURA     " +
            "SARAH     " +
            "KIMBERLY  " +
            "DEBORAH   " +
            "JESSICA   " +
            "SHIRLEY   " +
            "CYNTHIA   " +
            "ANGELA    " +
            "MELISSA  " +
            "DOROTHY   " +
            "LISA      " +
            "NANCY     " +
            "KAREN     " +
            "BETTY     " +
            "HELEN     " +
            "SANDRA    " +
            "DONNA     " +
            "CAROL     " +
            "RUTH      " +
            "SHARON    " +
            "MICHELLE  " +
            "LAURA     " +
            "SARAH     " +
            "KIMBERLY  " +
            "DEBORAH   " +
            "JESSICA   " +
            "SHIRLEY   " +
            "CYNTHIA   " +
            "ANGELA    " +
            "MELISSA   " +
            "BRENDA    " +
            "AMY       " +
            "AMY       " +
            "ANNA      " +
            "REBECCA   " +
            "VIRGINIA  " +
            "KATHLEEN  " +
            "PAMELA    " +
            "MARTHA    " +
            "DEBRA     " +
            "AMANDA    " +
            "STEPHANIE " +
            "CAROLYN   " +
            "CHRISTINE " +
            "MARIE     " +
            "JANET     " +
            "ANGELA    " +
            "MELISSA   " +
            "BRENDA    " +
            "AMY       " +
            "ANNA      " +
            "REBECCA   " +
            "VIRGINIA  " +
            "KATHLEEN  " +
            "PAMELA    " +
            "MARTHA    " +
            "DEBRA     " +
            "AMANDA    " +
            "STEPHANIE " +
            "CAROLYN   " +
            "CHRISTINE " +
            "MARIE     " +
            "JANET     " +
            "CATHERINE " +
            "FRANCES   " +
            "ANN       " +
            "ANNA      " +
            "REBECCA   " +
            "VIRGINIA  " +
            "KATHLEEN  " +
            "PAMELA    " +
            "MARTHA    " +
            "DEBRA     " +
            "AMANDA    " +
            "STEPHANIE " +
            "CAROLYN   " +
            "CHRISTINE " +
            "MARIE     " +
            "JANET     " +
            "ANGELA    " +
            "MELISSA   " +
            "BRENDA    " +
            "AMY       " +
            "ANNA      " +
            "REBECCA   " +
            "VIRGINIA  " +
            "KATHLEEN  " +
            "PAMELA    " +
            "MARTHA    " +
            "DEBRA     " +
            "AMANDA    " +
            "STEPHANIE " +
            "CAROLYN   " +
            "CHRISTINE " +
            "MARIE     " +
            "JANET     " +
            "CATHERINE " +
            "FRANCES   " +
            "ANN       " +
            "JOYCE     " +
            "DIANE     " +
            "ALICE     " +
            "JULIE     " +
            "HEATHER   " +
            "TERESA    " +
            "DORIS     " +
            "GLORIA    " +
            "EVELYN    " +
            "JEAN      " +
            "CHERYL    " +
            "MILDRED   " +
            "KATHERINE " +
            "JOAN      " +
            "ASHLEY    " +
            "JUDITH    " +
            "ROSE      " +
            "JANICE    " +
            "KELLY     " +
            "NICOLE    " +
            "JUDY      " +
            "CHRISTINA " +
            "KATHY     " +
            "THERESA   " +
            "BEVERLY   " +
            "DENISE    " +
            "TAMMY     " +
            "IRENE     " +
            "JANE      " +
            "LORI      " +
            "RACHEL    " +
            "MARILYN   " +
            "ANDREA    " +
            "KATHRYN   " +
            "LOUISE    " +
            "SARA      " +
            "ANNE      " +
            "JACQUELINE" +
            "WANDA     " +
            "BONNIE    " +
            "JULIA     " +
            "RUBY      " +
            "LOIS      " +
            "TINA      " +
            "PHYLLIS   " +
            "NORMA     " +
            "PAULA     " +
            "DIANA     " +
            "ANNIE     " +
            "LILLIAN   " +
            "EMILY     " +
            "ROBIN     " +
            "PEGGY     " +
            "CRYSTAL   " +
            "GLADYS    " +
            "RITA      " +
            "DAWN      " +
            "CONNIE    " +
            "FLORENCE  " +
            "TRACY     " +
            "EDNA      " +
            "TIFFANY   " +
            "CARMEN    " +
            "ROSA      " +
            "CINDY     " +
            "GRACE     " +
            "WENDY     " +
            "VICTORIA  " +
            "EDITH     " +
            "KIM       " +
            "SHERRY    " +
            "SYLVIA    " +
            "JOSEPHINE " +
            "THELMA    " +
            "SHANNON   " +
            "SHEILA    " +
            "ETHEL     " +
            "ELLEN     " +
            "ELAINE    " +
            "MARJORIE  " +
            "CARRIE    " +
            "CHARLOTTE " +
            "MONICA    " +
            "ESTHER    " +
            "PAULINE   " +
            "EMMA      " +
            "JUANITA   " +
            "ANITA     " +
            "RHONDA    " +
            "HAZEL     " +
            "AMBER     " +
            "EVA       " +
            "DEBBIE    " +
            "APRIL     " +
            "LESLIE    " +
            "CLARA     " +
            "LUCILLE   " +
            "JAMIE     " +
            "JOANNE    " +
            "ELEANOR   " +
            "VALERIE   " +
            "DANIELLE  " +
            "MEGAN     " +
            "ALICIA    " +
            "SUZANNE   " +
            "MICHELE   " +
            "GAIL      " +
            "BERTHA    " +
            "DARLENE   " +
            "VERONICA  " +
            "JILL      " +
            "ERIN      " +
            "GERALDINE " +
            "LAUREN    " +
            "CATHY     " +
            "JOANN     " +
            "LORRAINE  " +
            "LYNN      " +
            "SALLY     " +
            "REGINA    " +
            "DENISE    " +
            "TAMMY     " +
            "IRENE     " +
            "JANE      " +
            "LORI      " +
            "RACHEL    " +
            "MARILYN   " +
            "ANDREA    " +
            "KATHRYN   " +
            "LOUISE    " +
            "SARA      " +
            "ANNE      " +
            "JACQUELINE" +
            "WANDA     " +
            "BONNIE    " +
            "JULIA     " +
            "RUBY      " +
            "LOIS      " +
            "TINA      " +
            "PHYLLIS   " +
            "NORMA     " +
            "PAULA     " +
            "DIANA     " +
            "ANNIE     " +
            "LILLIAN   " +
            "EMILY     " +
            "ROBIN     " +
            "PEGGY     " +
            "CRYSTAL   " +
            "GLADYS    " +
            "RITA      " +
            "DAWN      " +
            "CONNIE    " +
            "FLORENCE  " +
            "TRACY     " +
            "EDNA      " +
            "TIFFANY   " +
            "CARMEN    " +
            "ROSA      " +
            "CINDY     " +
            "GRACE     " +
            "WENDY     " +
            "VICTORIA  " +
            "EDITH     " +
            "KIM       " +
            "SHERRY    " +
            "SYLVIA    " +
            "JOSEPHINE " +
            "THELMA    " +
            "SHANNON   " +
            "SHEILA    " +
            "ETHEL     " +
            "ELLEN     " +
            "ELAINE    " +
            "MARJORIE  " +
            "CARRIE    " +
            "CHARLOTTE " +
            "MONICA    " +
            "ESTHER    " +
            "PAULINE   " +
            "EMMA      " +
            "JUANITA   " +
            "ANITA     " +
            "RHONDA    " +
            "HAZEL     " +
            "AMBER     " +
            "EVA       " +
            "DEBBIE    " +
            "APRIL     " +
            "LESLIE    " +
            "CLARA     " +
            "LUCILLE   " +
            "JAMIE     " +
            "JOANNE    " +
            "ELEANOR   " +
            "VALERIE   " +
            "DANIELLE  " +
            "MEGAN     " +
            "ALICIA    " +
            "SUZANNE   " +
            "MICHELE   " +
            "GAIL      " +
            "BERTHA    " +
            "DARLENE   " +
            "VERONICA  " +
            "JILL      " +
            "ERIN      " +
            "GERALDINE " +
            "LAUREN    " +
            "CATHY     " +
            "JOANN     " +
            "LORRAINE  " +
            "LYNN      " +
            "SALLY     " +
            "REGINA    " +
            "ERICA     " +
            "BEATRICE  " +
            "DOLORES   " +
            "BERNICE   " +
            "AUDREY    " +
            "YVONNE    " +
            "ANNETTE   " +
            "JUNE      " +
            "SAMANTHA  " ;

    public static List<String> getNames() {
        String[] nameArr = NAMES.split(" ");
        List<String> nameList = new ArrayList<>();
        for (int i = 0; i < nameArr.length; i++) {
            if(!nameArr[i].trim().equals("")) {
                nameList.add(nameArr[i].trim());
            }
        }
        return nameList;
    }

}
